# Name your project (must use underscores, no hyphens!)
name: 'duck_warehouse'
version: '1.0.0'
config-version: 2

profile: 'duck_warehouse'

# Tell dbt where to look for your files
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

# Set default materializations for our folder structure
models:
  duck_warehouse:
    staging:
      +materialized: view  # Staging models don't take up disk space
    marts:
      +materialized: table # Marts are saved physically for fast querying