name: 'duck_warehouse'
version: '1.0.0'
config-version: 2

profile: 'duck_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: "{{ env_var('DBT_PROJECT_DIR') }}/dbt_packages"