name: 'stats19_warehouse'
version: '1.0.0'
config-version: 2
profile: 'warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  duck_warehouse:
    +materialized: view
    
    staging:
      +materialized: view
    marts:
      +materialized: table

data_tests:
  +store_failures: true
  +schema: "dlq"