version: 2

models:
  - name: stg_casualties
    columns:
      - name: collision_index
        description: "Collision index identifier"

  - name: stg_collisions
    columns:
      - name: collision_index
        description: "Collision index identifier"

  - name: stg_vehicles
    columns:
      - name: collision_index
        description: "Collision index identifier"
